trigger:
- main

pool:
  vmImage: ubuntu-latest

# Pipelines > Stages > Jobs > Tasks(Steps)

stages:
- stage: Build

  jobs:
  - job: BuildJob1
    steps:
    - script: echo BuildJob1
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo more information
      displayName: 'Run a multi-line script'

  - job: BuildJob2
    dependsOn: BuildJob1
    steps:
    - script: echo BuildJob2
      displayName: 'Run a one-line script'

  - job: BuildJob3
    dependsOn: BuildJob2
    steps:
    - script: echo BuildJob3
      displayName: 'Run a one-line script'

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevJob1
    steps:
    - script: echo DevJob1
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo more information
      displayName: 'Run a multi-line script'

  - job: DevJob2
    dependsOn: DevJob1
    steps:
    - script: echo DevJob2
      displayName: 'Run a one-line script'

  - job: DevJob3
    dependsOn: DevJob2
    steps:
    - script: echo DevJob3
      displayName: 'Run a one-line script'

- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: QAJob1
    steps:
    - script: echo QAJob1
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo more information
      displayName: 'Run a multi-line script'

  - job: QAJob2
    dependsOn: QAJob1
    steps:
    - script: echo QAJob2
      displayName: 'Run a one-line script'

  - job: QAJob3
    dependsOn: QAJob2
    steps:
    - script: echo QAJob3
      displayName: 'Run a one-line script'

- stage: ProdDeploy
  dependsOn: QADeploy
  jobs:
  - job: ProdJob1
    steps:
    - script: echo ProdJob1
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo more information
      displayName: 'Run a multi-line script'

  - job: ProdJob2
    dependsOn: ProdJob1
    steps:
    - script: echo ProdJob2
      displayName: 'Run a one-line script'

  - job: ProdJob3
    dependsOn: ProdJob2
    steps:
    - script: echo ProdJob3
      displayName: 'Run a one-line script'