trigger:
- main

pool:
  vmImage: ubuntu-latest

# Pipelines > Stages > Jobs > Tasks(Steps)

stages:
- stage: Build
  jobs:
  - job: BuildJob1
    steps:
    - bash: echo Build Job 1
    - bash: echo $(pipeline_variable_01) Build Job 1

- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevJob1
    steps:
    - bash: echo Dev Job 1
    - bash: echo $(environment) Deploy Job 1
  
- stage: QADeploy
  variables:
    environment: QA
  dependsOn: 
  - Build
  - DevDeploy
  jobs:
  - job: QAJob1
    steps:
    - bash: echo QA Job 1
    - bash: echo $(environment) Deploy Job 1

- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn:
  - DevDeploy 
  - QADeploy
  jobs:
  - job: ProdJob1
    steps:
    - bash: Prod Job 1
    - bash: echo $(environment) Deploy Job 1
